default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: hoard
  password: hoard
  database: hoard_<%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
