default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: hoard
  password: hoard
  database: hoard_<%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

<% if ENV['DB_PORT_5432_TCP_ADDR'].present? %>
production:
  <<: *default
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  username: postgres
  password: postgres
<% else %>
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
<% end %>
